### ISSUE TITLE
Ability to Run rhq-metrics on Windows

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkular-metrics#113]
Add a start.bat file so rhq-metrics can run on Windows as well.

**Comment by burmanm** [comment]
Could we finally skip Windows versions <2008? Windows Server 2003 EOL is 14.7.2015. So instead of old .bat files we could use PowerShell scripts?

**Comment by mtho11** [comment]
> On 25 Feb 2015, at 04:09, Michael Burman <notifications@github.com> wrote:
> 
> Could we finally skip Windows versions <2008? Windows Server 2003 EOL is 14.7.2015. So instead of old .bat files we could use PowerShell scripts?
> 
> 
I like that idea. I think most Windows admins are using Powershell now anyway.

**Comment by stefannegrea** [comment]
We had this idea for RHQ but never got anywhere. This project is the perfect candidate for this kind of work.

**Comment by burmanm** [comment]
Well I don't have write access to this repository, but you can assign this to me (I've done PowerShell scripts before)

**Comment by mtho11** [comment]
Here is the Jira: https://issues.jboss.org/browse/HAWKULAR-1

**Comment by tsegismont** [comment]
Can we close this issue if there's a JIRA?

**Comment by burmanm** [comment]
Fine for me to close.

**Comment by tsegismont** [comment]
Closing, issue tracked by https://issues.jboss.org/browse/HAWKULAR-1
