### ISSUE TITLE
Remove extraneous '/data' from Metrics REST API

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkular-metrics#147]
This '/data' is not meaningful to the url and should be removed because it is not RESTful.

_Current Url Example:_ `http://127.0.0.1:8080/rhq-metrics/test/metrics/numeric/200/data?buckets=60&end=1423330182686&start=1423243782685`

**Comment by jsanda** [comment]
@mtho11 can you please recreate this in Jira?
