### ISSUE TITLE
Add Jenkins builds via cloudbees

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkular-metrics#41]
It would be nice to have our jenkins builds out on the cloud where customers can test out the latest stuff without having to setup and build the artifacts.

LiveOak project is already doing this:
https://projectodd.ci.cloudbees.com/job/liveoak/

**Comment by stefannegrea** [comment]
This was resolved recently by publishing Travis snapshots builds to the JBoss Nexus repository.
